using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using UnityEngine;
using UnityEngine.UI;

public class AquariumUpdate : MonoBehaviour {

    public FishArea fishArea;
    public Slider healthSlider;
    public Slider aquariumTemperatureSlider;
    public Text foodCountText;
    public Text hourText;
    public Text externalTemperatureText;
    public RawImage wheaterImage;
    public Light directionalLight;
    private float accumulatedTime;
    private float second;
    private DateTime lastFoodHour;
    private float timeChangeWheater;
    private float timeChangeExternalTemperature;
    private bool isNight;
    public Texture2D sunImage;
    public Texture2D sunAndCloudImage;
    public Texture2D snowImage;
    public Texture2D rainImage;
    public Texture2D moonImage;


    // Use this for initialization
    void Start () {
        if (AquariumProperties.configs != null)
        {
            AquariumProperties.currentTimeSpeed = (AquariumProperties.TimeSpeed)AquariumProperties.configs.timeSpeed;
        } else
        {
            AquariumProperties.currentTimeSpeed = AquariumProperties.TimeSpeed.Normal;
        }        
        AquariumProperties.aquariumTemperature = 25.0f;
        AquariumProperties.externalTemperature = 25.0f;
        AquariumProperties.heaterTemperature = 19;
        AquariumProperties.lightIntensity = 2;
        AquariumProperties.externalLightIntensity = 2;
        AquariumProperties.sensorLightIntensity = 0;
        AquariumProperties.foodAvailable = 10;
        AquariumProperties.currentWheater = AquariumProperties.Wheater.Sun;
        AquariumProperties.aquariumHour = DateTime.ParseExact("08:00", "HH:mm", CultureInfo.InvariantCulture);
        lastFoodHour = DateTime.ParseExact("08:00", "HH:mm", CultureInfo.InvariantCulture);
        switch (AquariumProperties.currentTimeSpeed)
        {
            case AquariumProperties.TimeSpeed.Fast:
                AquariumProperties.timeSpeedMultiplier = 30;
                break;
            case AquariumProperties.TimeSpeed.Normal:
                AquariumProperties.timeSpeedMultiplier = 60;
                break;
            case AquariumProperties.TimeSpeed.Slow:
                AquariumProperties.timeSpeedMultiplier = 120;
                break;
            case AquariumProperties.TimeSpeed.RealTime:
                AquariumProperties.timeSpeedMultiplier = 3600;
                break;
        }
    }
	
	// Update is called once per frame
	void Update () {        
        updateTime();        
	}

    void updateTime()
    {
        Debug.Log(AquariumProperties.aquariumHour);
        accumulatedTime += Time.deltaTime;        
        if (AquariumProperties.currentTimeSpeed != AquariumProperties.TimeSpeed.RealTime)
        {
            if (accumulatedTime >= AquariumProperties.timeSpeedMultiplier)
            {                
                AquariumProperties.aquariumHour = AquariumProperties.aquariumHour.AddHours(1);
                accumulatedTime = 0;
            }
        } else
        {
            AquariumProperties.aquariumHour = AquariumProperties.aquariumHour.AddSeconds(Time.deltaTime);
        }
        hourText.text = AquariumProperties.aquariumHour.ToString("HH:ss");
        second += Time.deltaTime;
        if (second >= 1)
        {
            updateHealth();
            updateFood();
            updateWheater();
            updateTemperature();
            //updateLightItensity();
            updateHealthCoefficient();
            second = 0;
        }
    }

    void updateHealth()
    {        
        float totalLife = 0;
        int countFishes = 0;
        for (int i = 0; i < fishArea.fishes.Count; i++)
        {
            if (fishArea.fishes[i].gameObject.activeSelf)
            {
                totalLife += fishArea.fishes[i].life;
                ++countFishes;
            }

        }
        if (countFishes > 0)
        {
            AquariumProperties.aquariumHealth = totalLife / countFishes;
            healthSlider.value = AquariumProperties.aquariumHealth * 0.01f;
        }
        else
        {
            AquariumProperties.aquariumHealth = 0;
            healthSlider.value = 0;
        }
    }

    void updateFood()
    {      
        if ((AquariumProperties.aquariumHour.Subtract(lastFoodHour).Hours >= 2) && AquariumProperties.foodAvailable < 10)
        {
            AquariumProperties.foodAvailable++;
            lastFoodHour = AquariumProperties.aquariumHour;
        }
        foodCountText.text = AquariumProperties.foodAvailable.ToString();        
    }

    void updateWheater()
    {
        isNight = AquariumProperties.aquariumHour >= DateTime.ParseExact("18:30", "HH:mm", CultureInfo.InvariantCulture) && AquariumProperties.aquariumHour <= DateTime.ParseExact("04:59", "HH:mm", CultureInfo.InvariantCulture);
        timeChangeWheater++;
        if (timeChangeWheater >= AquariumProperties.timeSpeedMultiplier * 4)
        {
            bool acceptable = false;
            do
            {
                int wheater = UnityEngine.Random.Range(0, 4);
                if (isNight && (wheater == 0 || wheater == 1)) 
                {
                    acceptable = false;
                } else if (!isNight && wheater == 4)
                {
                    acceptable = false;
                } else
                {
                    acceptable = true;
                }
            } while (!acceptable);            
            AquariumProperties.currentWheater = (AquariumProperties.Wheater) UnityEngine.Random.Range(0, 4);
            timeChangeWheater = 0;
        }
        timeChangeExternalTemperature++;
        if (timeChangeExternalTemperature >= AquariumProperties.timeSpeedMultiplier)
        {
            switch (AquariumProperties.currentWheater)
            {
                case AquariumProperties.Wheater.Sun:
                    wheaterImage.texture = sunImage;
                    AquariumProperties.externalTemperature = UnityEngine.Random.Range(25, 43);
                    AquariumProperties.externalLightIntensity = 0.5f;
                    break;
                case AquariumProperties.Wheater.SunAndCloud:
                    wheaterImage.texture = sunAndCloudImage;
                    AquariumProperties.externalTemperature = UnityEngine.Random.Range(18, 33);
                    AquariumProperties.externalLightIntensity = 0.3f;
                    break;
                case AquariumProperties.Wheater.Snow:
                    wheaterImage.texture = snowImage;
                    AquariumProperties.externalTemperature = UnityEngine.Random.Range(-2, 5);
                    AquariumProperties.externalLightIntensity = isNight ? 0.0f : 0.2f;
                    break;
                case AquariumProperties.Wheater.Rain:
                    wheaterImage.texture = rainImage;
                    AquariumProperties.externalTemperature = UnityEngine.Random.Range(10, 24);
                    AquariumProperties.externalLightIntensity = isNight ? 0.0f : 0.2f;
                    break;
                case AquariumProperties.Wheater.Moon:
                    wheaterImage.texture = moonImage;
                    AquariumProperties.externalTemperature = UnityEngine.Random.Range(8, 21);
                    AquariumProperties.externalLightIntensity = 0.0f;
                    break;
            }
            externalTemperatureText.text = AquariumProperties.externalTemperature + "ºC";
            timeChangeExternalTemperature = 0;
        }                
    }

    void updateTemperature()
    {       
        float heaterAquariumDiff = AquariumProperties.heaterTemperature - AquariumProperties.aquariumTemperature;        
        float externalAquariumDiff = AquariumProperties.externalTemperature - AquariumProperties.aquariumTemperature;
        AquariumProperties.temperatureCoefficient = externalAquariumDiff / (AquariumProperties.timeSpeedMultiplier * 3) + heaterAquariumDiff / ((AquariumProperties.timeSpeedMultiplier * 2.5f));
        AquariumProperties.aquariumTemperature += AquariumProperties.temperatureCoefficient;
        aquariumTemperatureSlider.value = AquariumProperties.aquariumTemperature;
    }

    void updateLightItensity()
    {
        AquariumProperties.lightIntensity = AquariumProperties.externalLightIntensity + AquariumProperties.sensorLightIntensity;
        directionalLight.intensity = AquariumProperties.lightIntensity;
    }

    void updateHealthCoefficient()
    {
        float temperatureCoefficient = 0;
        float lightCoefficient = 0;
        if (AquariumProperties.aquariumTemperature >= AquariumProperties.MIN_TEMPERATURE_SUPPORTED && AquariumProperties.aquariumTemperature <= AquariumProperties.MAX_TEMPERATURE_SUPPORTED)
        {
            temperatureCoefficient = 0;
        } else if (AquariumProperties.aquariumTemperature > AquariumProperties.MAX_TEMPERATURE_SUPPORTED)
        {
            temperatureCoefficient = (AquariumProperties.aquariumTemperature - AquariumProperties.MAX_TEMPERATURE_SUPPORTED) * 0.03f;
        } else if (AquariumProperties.aquariumTemperature < AquariumProperties.MIN_TEMPERATURE_SUPPORTED)
        {
            temperatureCoefficient = (AquariumProperties.MIN_TEMPERATURE_SUPPORTED - AquariumProperties.aquariumTemperature) * 0.03f;
        }
        float maxLight = isNight ? AquariumProperties.MAX_LIGHT_SUPPORTED_NIGHT : AquariumProperties.MAX_LIGHT_SUPPORTED;
        float minLight = isNight ? AquariumProperties.MIN_LIGHT_SUPPORTED_NIGHT : AquariumProperties.MIN_LIGHT_SUPPORTED;
        if (AquariumProperties.lightIntensity >= minLight && AquariumProperties.lightIntensity <= maxLight)
        {
            lightCoefficient = 0;
        } else if (AquariumProperties.lightIntensity > maxLight)
        {
            lightCoefficient = (AquariumProperties.lightIntensity - maxLight); 
        } else if (AquariumProperties.lightIntensity < minLight)
        {
            lightCoefficient = (minLight - AquariumProperties.lightIntensity);
        }
        AquariumProperties.lossLifeCoefficient = /*lightCoefficient +*/ temperatureCoefficient;
    }

    public static void socketCallback(string message)
    {
        string tag = message.Substring(0, message.IndexOf("|"));
        string value = message.Substring(message.IndexOf("|") + 1);
        if (tag.Equals("TEMP"))
        {
            AquariumProperties.heaterTemperature = float.Parse(value);
            Debug.Log(AquariumProperties.heaterTemperature);
        }
    }
}
